[package]
name = "sorcerers"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
macroquad = "0.4.14"
image = { version = "0.24", features = ["jpeg", "webp"] }
uuid = { version = "1.18.1", features = ["v4", "serde"] }
tokio = { version = "1.48.0", features = ["full"] }
socket2 = "0.6.1"
tokio-util = { version = "0.7.17", features = ["codec"] }
tokio-serde = "0.9.0"
rmp = "0.8.14"
rmp-serde = "1.3.0"
serde = { version = "1.0.228", features = ["derive"] }

[[bin]]
name = "server"
path = "src/server/bin/main.rs"

[[bin]]
name = "client"
path = "src/client/bin/main.rs"

[lib]
name = "sorcerers"
path = "src/lib/mod.rs"
