[package]
name = "sorcerers"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.5.0"
crossbeam = "0.8.4"
oneshot = "0.1.11"
typetag = "0.2.21"
erased-serde = "0.4.9"
clap = { version = "4.5.53", features = ["derive"] }
convert_case = "0.10.0"
anyhow = "1.0.100"
macroquad = "0.4.14"
image = { version = "0.24", features = ["jpeg", "webp"] }
uuid = { version = "1.18.1", features = ["v4", "serde"] }
tokio = { version = "1.48.0", features = ["full"] }
socket2 = "0.6.1"
tokio-util = { version = "0.7.17", features = ["codec"] }
tokio-serde = "0.9.0"
rmp = "0.8.14"
rmp-serde = "1.3.0"
serde = { version = "1.0.228", features = ["derive"] }
rand = "0.9.2"
reqwest = { version = "0.12.24", features = ["blocking"]}

[[bin]]
name = "server"
path = "src/server/bin/main.rs"

[[bin]]
name = "client"
path = "src/client/bin/main.rs"

# [[bin]]
# name = "add-card"
# path = "src/cli/bin/main.rs"

[lib]
name = "sorcerers"
path = "src/lib/mod.rs"
